<?php

?>
<style>
    .popup-newsletter .block.newsletter {
        width: 80%;
    }
    .newsletter-content {
        display: none;
    }
    .newsletter-content .messages {
        display: none;
    }
    .newsletter-content h2 {
        text-transform: uppercase;
        font-size: 20px;
        font-weight: 600;
        line-height: initial;
        margin: 15px 0px;
    }
    .newsletter-content.block.newsletter .actions {
        display: block;
        margin-top: 15px;
        width: 100%;
    }
    .newsletter-content .actions .action.subscribe.primary {
        border-radius: 5px;
        width: 100%;
        display: block;
    }
</style>
<div class="block newsletter newsletter-content" id="popup-newsletter">
    <div class="messages">
        <div class="message message-error error">
            <div></div>
        </div>
    </div>
    <div class="intro">
        <p><?php echo __('subscribe to our news letter u will get our store updates .'); ?></p>
        <h2><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:'); ?></h2>
    </div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl(); ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:'); ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address'); ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe'); ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#popup-newsletter": {
            "Customer_Newsletter/js/process-popup-newsletter": {
                "popupTitle": "<?php /* @escapeNotVerified */ echo __('Newsletter'); ?>"
            }
        }
    }
</script>

